#!/bin/bash
# EXTENSIONS="
# @jupyter-widgets/jupyterlab-manager@2.0.0
# ipydagred3@0.2.5
# "

# jupyter labextension install $EXTENSIONS --no-build
# jupyter lab build --dev-build=False --minimize=False

jupyter server extension enable --py jupyterlab
